
modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
[[mods]]
modId="actuallyadditions"
version="${file.jarVersion}"
displayName="Actually Additions"
#logoFile="logo.png"
credits="Author: Ellpeck; Textures and Models: BootyToast, GlenthorLP, canitzp"
authors="Ellpeck"
description='''
Do you want Automation? Wireless Transport? Better Machines? A cup o' Coffee? Chests? Better Hoppers? Leaf Blowers? Faster Growth? Plants? Well, Actually Additions has all that and a lot more!
'''

[[dependencies.actuallyadditions]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.167,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.actuallyadditions]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
