
modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="actuallyadditions"
version="${file.jarVersion}"
displayName="Actually Additions"
#logoFile="logo.png"
credits="Author: Ellpeck; Textures and Models: BootyToast, GlenthorLP, canitzp; Porters: Flanks, MrBysco, ErrorMikey; 1.20+ Textures: Ridanisaurus"
authors="Ellpeck"
description='''
Do you want Automation? Wireless Transport? Better Machines? A cup o\' Coffee? Chests? Better Hoppers? Leaf Blowers? Faster Growth? Plants? Well, Actually Additions has all that and a lot more!
'''
[[mixins]]
config = "actuallyadditions.mixins.json"

[[dependencies.actuallyadditions]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.actuallyadditions]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
