modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/Ellpeck/ActuallyAdditions/issues"

[[mods]]
modId="actuallyadditions"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Ellpeck/ActuallyAdditions"
credits="Author: Ellpeck; Textures and Models: BootyToast, GlenthorLP, canitzp; Porters: Flanks, MrBysco, ErrorMikey; 1.20+ Textures: Ridanisaurus"
authors="Ellpeck"
description='''
Do you want Automation? Wireless Transport? Better Machines? A cup o\' Coffee? Chests? Better Hoppers? Leaf Blowers? Faster Growth? Plants? Well, Actually Additions has all that and a lot more!
'''

[[mixins]]
config = "actuallyadditions.mixins.json"

[[dependencies.actuallyadditions]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.actuallyadditions]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
